export enum API_COMMON_MESSAGES {
  SUCCESS = 'Request was successful',
  CREATED = 'Resource created successfully',
  UPDATED = 'Resource updated successfully',
  DELETED = 'Resource deleted successfully',
  NOT_FOUND = 'Resource not found',
  UNAUTHORIZED = 'Unauthorized access',
  FORBIDDEN = 'Forbidden access',
  BAD_REQUEST = 'Bad request',
  INTERNAL_SERVER_ERROR = 'Internal server error',
  VALIDATION_ERROR = 'Validation error',
  CONFLICT = 'Conflict error',
  UNPROCESSABLE_ENTITY = 'Unprocessable entity',
  SERVICE_UNAVAILABLE = 'Service unavailable',
  GATEWAY_TIMEOUT = 'Gateway timeout',
  NOT_IMPLEMENTED = 'Not implemented',
  METHOD_NOT_ALLOWED = 'Method not allowed',
  PRECONDITION_FAILED = 'Precondition failed',
  TOO_MANY_REQUESTS = 'Too many requests',
  NOT_ACCEPTABLE = 'Not acceptable',
}

export enum API_COMMON_STATUS_CODES {
  SUCCESS = 200,
  CREATED = 201,
  UPDATED = 204,
  DELETED = 203, // soft delete
  NOT_FOUND = 404,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  BAD_REQUEST = 400,
  INTERNAL_SERVER_ERROR = 500,
  VALIDATION_ERROR = 402,
  CONFLICT = 409,
  UNPROCESSABLE_ENTITY = 422,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504,
  NOT_IMPLEMENTED = 501,
  METHOD_NOT_ALLOWED = 405,
  PRECONDITION_FAILED = 412,
  TOO_MANY_REQUESTS = 429,
  NOT_ACCEPTABLE = 406,
}
